### PR TITLE
catch GL frame errors, fix errors from a stencil call on Intel/OSX, fixes #192

### LINKED ISSUE #192: Second computer screen blank on OSX
**Describe the bug**
The computer to the left appears with a black screen. Keyboard input is not visible as on windows build.

**To Reproduce**
Build and run on OSX. Observe the left computer.

### PR DESCRIPTION
**Pull request by Meisaka**
## Description

Adds calls to glGetError at the beginning and end of frames to prevent them from leaking into other calls.
Adds the ability to fallback to OpenGL 3.3, if the 4.0 isn't supported (because I hate manually patching this in every time).
Fixes a GL error where the GL requires a fragment shader in a pure stencil/depth pipeline.

## Motivation and Context

See issue (https://github.com/trillek-team/tec/issues/192)
## How Has This Been Tested?

Built and run on MacOS 10.12.6, with Intel HD Graphics 3000 (GL 3.3) - The virtual computer in entity 101 rendered it's screen.
With verbose flag "-v" no GL errors reported.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: client/main.cpp [hunk 1]
```diff
@@ -96,11 +96,15 @@ int main(int argc, char* argv[]) {
 
 	const unsigned int window_width = game.config_script->environment.get_or("window_width", WINDOW_WIDTH);
 	const unsigned int window_height = game.config_script->environment.get_or("window_height", WINDOW_HEIGHT);
+	std::string window_title = "Trillek Engine 0.1";
 
 	log->info("Initializing OpenGL...");
-	if (!os.InitializeWindow(window_width, window_height, "TEC 0.1", 4, 0)) {
-		log->info("Exiting. The context wasn't created properly please update drivers and try again.");
-		exit(1);
+	if (!os.InitializeWindow(window_width, window_height, window_title, 4, 0)) {
```
Comment (adam4813) [inline client/main.cpp:102]: Nice idea to have a fallback!

**Review by adam4813 — APPROVED** [review]
